spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expirationTime: 86000000

razorpay:
  key: rzp_test_WObwjOPe6G2PMF
  secret: SxZpTiOxMM0FWzatLBW2S76A
